version: '3'
services:
  lb:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - service1

  service1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge