name: CICD

on:
  push:
    branches: [sit]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: ./gradlew build

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Delete old container
        run: docker rmi $ (docker images -a -q)
      - name: Run docker container
        run: docker-compose up -d
